server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/cinema/api/v1/movies/**
        - id: showtimes-service
          uri: lb://SHOWTIMES-SERVICE
          predicates:
            - Path=/cinema/api/v1/showtimes/**
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/cinema/api/v1/users/**
        - id: bookings-service
          uri: lb://BOOKINGS-SERVICE
          predicates:
            - Path=/cinema/api/v1/bookings/**