server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: moviesservice
          uri: lb://movies-service
          predicates:
            - Path=/api/v1/movies/**
        - id: showtimesservice
          uri: lb://showtimes-service
          predicates:
            - Path=/api/v1/showtimes/**
        - id: usersservice
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**
        - id: bookingsservice
          uri: lb://BOOKINGS-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
